Repository Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend, pull requests merged in 2022-10, with the labels that each got.

#4 Replaced tailwind with bootstrap
  package-lock.json
  package.json
  src/App.js
  src/Components/Navbar.js
  src/Components/Spinner.js
  src/Components/TweetContainer.js
  src/index.css
  src/index.js
  tailwind.config.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Layout fully complete
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  src/App.css
  src/App.js
  src/Components/Navbar.js
  src/Components/TweetContainer.js
  src/index.js
  src/logo.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 Completed
  package-lock.json
  package.json
  src/App.js
  src/Components/Navbar.js
  src/Components/Tweet.js
  src/Components/TweetContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 updated readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#20 Feature : Acknowledge the Contributors by adding Contributors Section…
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#26 Issue #25
  src/Components/TweetContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Spinner improvements
  src/App.js
  src/Components/TweetContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 Added UI
  Remote Bird Jobs-UI/Logo.svg
  Remote Bird Jobs-UI/Web-UI.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 feat: improve selection
  package-lock.json
  package.json
  src/Components/Navbar.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#27 improvement card layout, responsive & flexbox to grid
  src/App.css
  src/Components/TweetContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#31 #28 handle empty response
  src/App.js
  src/Components/Spinner.js
  src/Components/TweetContainer.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#36 Topic label removed
  src/Components/Navbar.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Fix for calendar date change issue
  package-lock.json
  package.json
  src/Components/Navbar.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#43 All UI update
  src/App.css
  src/Components/Logo.svg
  src/Components/Navbar.css
  src/Components/Navbar.js
  src/Components/Tweet.js
  src/Components/TweetContainer.css
  src/Components/TweetContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 Checkbox for WFH
  src/Components/Navbar.css
  src/Components/Navbar.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 Reduced the margins
  src/Components/Navbar.css
Labels: hacktoberfest, hacktoberfest-accepted

#49 Added mobile UI
  Mobile UI/Logo.svg
  Mobile UI/Mobile UI.png
Labels: hacktoberfest, hacktoberfest-accepted

#48 Adjusted Date Picker Logic
  src/Components/Navbar.css
  src/Components/Navbar.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#56 Tweetcontainer centered
  src/Components/TweetContainer.js
Labels: hacktoberfest, hacktoberfest-accepted

#57 fixed navbar
  src/App.css
  src/Components/Navbar.css
  src/Components/TweetContainer.css
Labels: hacktoberfest, hacktoberfest-accepted

#58 Navbar padding
  src/Components/Navbar.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Date picker border radius
  src/Components/Navbar.css
Labels: hacktoberfest, hacktoberfest-accepted
